# Generated by Django 5.2.8 on 2025-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='intro',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
